spring:
  application:
    name: spring-plus

  datasource:
    url: jdbc:mysql://localhost:3306/${DB_SCHEME}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret:
    key: ${SECRET_KEY}

